### ISSUE TITLE
IllegalStateException: X-RateLimit-Limit header is required

### ISSUE THREAD

**Issue by chrisrohr** [kiwiproject/kiwiproject-changelog#240]
If you have a large number of commits for a release, you get the following error:

```
java.lang.IllegalStateException: X-RateLimit-Limit header is required
        at org.kiwiproject.changelog.extension.HttpHeadersExtensionsKt.firstValueAsLongOrThrow$lambda$1(HttpHeadersExtensions.kt:11)
        at java.base/java.util.OptionalLong.orElseThrow(OptionalLong.java:273)
        at org.kiwiproject.changelog.extension.HttpHeadersExtensionsKt.firstValueAsLongOrThrow(HttpHeadersExtensions.kt:11)
        at org.kiwiproject.changelog.github.GitHubResponse$Companion.from(GitHubResponse.kt:53)
        at org.kiwiproject.changelog.github.GitHubApi.sendRequest(GitHubApi.kt:102)
        at org.kiwiproject.changelog.github.GitHubApi.sendRequestAndCheckRateLimit(GitHubApi.kt:71)
        at org.kiwiproject.changelog.github.GitHubApi.get(GitHubApi.kt:35)
        at org.kiwiproject.changelog.github.GitHubReleaseManager.checkReleaseDoesNotExist(GitHubReleaseManager.kt:67)
        at org.kiwiproject.changelog.github.GitHubReleaseManager.createRelease(GitHubReleaseManager.kt:31)
        at org.kiwiproject.changelog.ChangelogGenerator.writeChangeLog(ChangelogGenerator.kt:69)
        at org.kiwiproject.changelog.ChangelogGenerator.generate(ChangelogGenerator.kt:37)
        at org.kiwiproject.changelog.App.run(App.kt:263)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.kiwiproject.changelog.App$Companion.execute$changelog_generator(App.kt:317)
        at org.kiwiproject.changelog.App$Companion.main(App.kt:310)
        at org.kiwiproject.changelog.App.main(App.kt)
```

This happened when I had 103 issues in the change log.

**Comment by sleberknight** [comment]
This is not when _sending_ a request, it's when _receiving_ a response from a `GET`. The code expects there will always be an `X-RateLimit-Limit` header, but apparently it's not always present even though I thought the GitHub API docs say it is there when there is pagination. You can see the `sendRequestAndCheckRateLimit` where the code calls `HttpHeaderExtensions.firstValueAsLongOrThrow`. But regardless of what the GitHub API docs say, we can't assume that header is always present.

**Comment by sleberknight** [comment]
Just looked at the code. Here's a comment at the beginning of the `checkReleaseDoesNotExist` method which is called from `createRelease`:

```java
        // Implementation Note:
        // This gets the 100 most recent releases. We do not bother paginating,
        // and assume that no one would realistically try to release something
        // that old. So, if they do, we will rely on GitHub returning a 422 if
        // the release exists.
```

We add a `per_page=`100` to the `releases` URL to get back only the most 100 releases. This code is checking that the release doesn't already exist within the 100 most recent releases, which seems at least somewhat reasonable.

But I just reviewed the [Checking the status of your rate limit](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#checking-the-status-of-your-rate-limit) section of the _Rate limits for the REST API_ page, and it certainly seems that you should be able to count on that header.

@chrisrohr which repository was this and can you tell me the parameters you used when trying to do the release, so I can replicate the problem and figure out what is _really_ going on here.

**Comment by sleberknight** [comment]
I changed the issue title to (I think) better reflect the problem, which I don't think is related to the number of commits. Instead, it seems that there are times when the GitHub API may return a response from a paginated endpoint that does _not_  contain the `X-RateLimit-Limit`.

**Comment by sleberknight** [comment]
I just found the discussion: [Missing X-RateLimit Header when GET /releases with token?](https://github.com/orgs/community/discussions/140079) which was from September 29, 2024 (very recent).

This may be what caused the `IllegalStateException` originally for you @chrisrohr and why, several days later on October 6, I did not experience the issue when I ran the command to generate a changelog.

**Comment by sleberknight** [comment]
Several people in that "Missing X-RateLimit" header discussion indicate the problem was "fixed" on October 4. See [here](https://github.com/orgs/community/discussions/140079#discussioncomment-10843669) or [here](https://github.com/orgs/community/discussions/140079#discussioncomment-10844309)

**Comment by sleberknight** [comment]
So, @chrisrohr go ahead and test again, and if it works, we will assume the root cause was a GitHub problem that has now been resolved.

**Comment by sleberknight** [comment]
I am closing this as "stale" and chalking it up to the temporary GtHub problem mentioned in the above comments.
